with-expecter: true
dir: "mocks"
outpkg: "mocks"
packages:
  homework/internal/storage:
    interfaces:
      Storage:
  homework/internal/service:
    interfaces:
      PackageService:
      ValidationService:
  homework/pkg/hash:
    interfaces:
      Hasher: