with-expecter: true
dir: "mocks"
outpkg: "mocks"
packages:
  homework/internal/storage:
    config:
      recursive: True
    interfaces:
      Storage:
  homework/internal/service/package:
    config:
      recursive: True
    interfaces:
      PackageService:
  homework/internal/service:
    config:
      recursive: True
    interfaces:
      ValidationService: