'TODO: remove order_service and models
@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_AS_SKETCH()

title Контейнер-диаграмма "Утилита для управления ПВЗ"

Person(operator, "Оператор ПВЗ", "Оператор ПВЗ, который может выдавать и принимать заказы")

System_Boundary(c1, "CLI") {
    Container(cli, "View - Командная утилита для Оператора ПВЗ", "Поддерживает множество взаимодействий с заказами")
    Container(order_service, "Service - Сервис обработки заказов", "Accept, ReturnToCourier, Issue, Return, ListReturns, ListOrders, PrintList", "Предоставляет основную функциональность с помощью валидации и обработки пользовательского ввода и взаимодействия с базой данных")
    Container(models, "Models", "Структура Order", "Сущность Заказа")
    ContainerDb(db, "Storage - база данных", "Реляционная база данных PostgreSQL", "Поддерживает консистентность данных о заказах")
}

Rel(operator, cli, "Uses")
Rel(cli, order_service, "Uses", "Asynchronous")
Rel_Neighbor(order_service, db, "Reads from and writes to", "Asynchronous")
Rel(order_service, models, "Uses")
@enduml