services:
#  NOTES:
#  1) POSTGRES_HOST should be equal to service - "db"
#  2) Чтобы настроить постгрес на новом Image(после удаления например, нужно
#  установить в .env файлах user, password = postgres, postgres для первого подключения
#  3) Порты - Если приложение запускается в докере, порты не следует задавать вообще, у db и db_test в конфиге
#  порт должны быть одинаковыми - 5432, т.к хостом является контейнер db и db_test
#  4) Порты для запуска приложения не из докера (localhost) должны быть прописаны (3333:5432)
#  app:
#    container_name: go
#    build: .
#    restart: on-failure
#    depends_on:
#      - db
#      - db_test
#    networks:
#      - postgres

  db:
    image: postgres
    container_name: pg
    tty: true
#    если не указать Postgres_password из env_file или напрямую
#    как в db_test - postgres контейнер будет рестартиться!
    env_file:
      - .env
    restart: on-failure
    networks:
      - postgres
    ports:
      - 3333:5432

  db_test:
    image: postgres
    container_name: pg_test
    tty: true
#   on first launch environment should be set to postgres, both user and password!
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: on-failure
    networks:
      - postgres
    ports:
      - 4444:5432

networks:
  postgres:
    driver: bridge