// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// GenerateHash provides a mock function with given fields:
func (_m *MockHasher) GenerateHash() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GenerateHash")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockHasher_GenerateHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateHash'
type MockHasher_GenerateHash_Call struct {
	*mock.Call
}

// GenerateHash is a helper method to define mock.On call
func (_e *MockHasher_Expecter) GenerateHash() *MockHasher_GenerateHash_Call {
	return &MockHasher_GenerateHash_Call{Call: _e.mock.On("GenerateHash")}
}

func (_c *MockHasher_GenerateHash_Call) Run(run func()) *MockHasher_GenerateHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHasher_GenerateHash_Call) Return(_a0 string) *MockHasher_GenerateHash_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockHasher_GenerateHash_Call) RunAndReturn(run func() string) *MockHasher_GenerateHash_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
