{
 "title": "CLI",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "rate_goroutines_1m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(go_goroutines[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Duration",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(cli_http_cli_duration_bucket[1h])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(cli_http_cli_duration_bucket[1h])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(cli_http_cli_duration_bucket[1h])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(cli_http_cli_duration_bucket[1h])))",
     "legendFormat": "P75"
    }
   ]
  },
  {
   "title": "method_calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "cli_http_cli_total", "legendFormat": "__auto" }
   ]
  }
 ]
}