scrape_configs:
  - job_name: cli
    scrape_interval: 5s
    static_configs:
      - targets: ['otel-collector:8888']
      - targets: ['otel-collector:8889']
  - job_name: jaeger
    scrape_interval: 10s
    static_configs:
      - targets: [ 'jaeger:14269' ]